version: "3.9"

volumes:
  pgdata:

networks:
  crud_net:

services:
  potgredb:
    image: postgres:latest
    environment:
      POSTGRES_DB: "crud_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin123"
    ports:
      - "5555:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d crud_db"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - .:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
      - ./logs:/var/log
    networks:
      - crud_net
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin1@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1GB
    networks:
      - crud_net
  nginx:
    image: nginx:latest
    volumes:
      - .:/nginx
    ports:
      - "8888:80"
    networks:
      - crud_net
  backend:
    build: .
    depends_on:
      - postgredb
    ports:
      - "7777:8080"
    restart: unless-stopped
    networks:
      - crud_net
    command: bash -c "gunicorn -b 127.0.0.1:7777 stocks_products.wsgi"